"""Generate undo shell scripts from action log files."""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import TextIO

from rich.console import Console

from duplicates_detector.filters import format_size


def _shell_quote(s: str) -> str:
    """Escape a string for safe embedding in double-quoted bash strings.

    Escapes: backslash, double-quote, dollar sign, backtick.
    Literal newlines are preserved — they are safe inside double quotes
    and must remain intact so shell commands reference the correct path.
    """
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def _sanitize_comment(s: str) -> str:
    """Replace control characters that would break a shell comment line."""
    return s.replace("\n", "\\n").replace("\r", "\\r")


def parse_action_log(path: Path, *, console: Console | None = None) -> tuple[list[dict], int, int, int]:
    """Parse a JSON-lines action log, skipping dry-run and malformed entries.

    Returns ``(records, total, skipped_dry_run, skipped_malformed)`` where
    *records* is the list of valid, non-dry-run action dicts.
    """
    if console is None:
        console = Console(stderr=True)

    records: list[dict] = []
    total = 0
    skipped_dry_run = 0
    skipped_malformed = 0

    try:
        with path.open(encoding="utf-8", errors="replace") as f:
            for lineno, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                total += 1
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    console.print(f"[yellow]Warning: Skipping malformed line {lineno} in {path}[/yellow]")
                    skipped_malformed += 1
                    continue
                if not isinstance(record, dict):
                    console.print(f"[yellow]Warning: Skipping non-object line {lineno} in {path}[/yellow]")
                    skipped_malformed += 1
                    continue
                if "action" not in record or not isinstance(record["action"], str):
                    console.print(f"[yellow]Warning: Skipping line {lineno} in {path} (missing 'action')[/yellow]")
                    skipped_malformed += 1
                    continue
                if "path" not in record or not isinstance(record["path"], str):
                    console.print(f"[yellow]Warning: Skipping line {lineno} in {path} (missing 'path')[/yellow]")
                    skipped_malformed += 1
                    continue
                if record.get("dry_run"):
                    skipped_dry_run += 1
                    continue
                records.append(record)
    except OSError as exc:
        console.print(f"[red]Error reading log file: {exc}[/red]")
        raise SystemExit(1) from None

    return records, total, skipped_dry_run, skipped_malformed


def generate_undo_script(
    records: list[dict],
    *,
    log_path: Path,
    total_records: int,
    skipped_dry_run: int,
    skipped_malformed: int,
    output: TextIO = sys.stdout,
) -> None:
    """Write a bash undo script to the given output stream."""
    reversible = sum(1 for r in records if r["action"] in ("moved", "hardlinked", "symlinked", "reflinked"))
    warnings_count = sum(1 for r in records if r["action"] in ("trashed", "deleted", "photos_trash"))

    w = output.write

    # Header
    w("#!/usr/bin/env bash\n")
    w("# Undo script generated by duplicates-detector\n")
    w(f"# Source log: {_sanitize_comment(str(log_path.resolve()))}\n")
    w(f"# Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S')}\n")
    w(f"# Actions: {total_records} total ({reversible} reversible, {warnings_count} warnings")
    if skipped_dry_run:
        w(f", {skipped_dry_run} skipped dry-run")
    if skipped_malformed:
        w(f", {skipped_malformed} skipped malformed")
    w(")\n\n")

    w("set -euo pipefail\n\n")

    # Confirmation prompt
    w(f'echo "This script will attempt to undo {reversible} file operations."\n')
    w('echo "WARNING: Restoring files may overwrite newer versions."\n')
    w('read -r -p "Continue? [y/N] " response\n')
    w('case "$response" in\n')
    w("    [yY][eE][sS]|[yY]) ;;\n")
    w('    *) echo "Aborted."; exit 1 ;;\n')
    w("esac\n\n")

    # Counters
    w("restored=0\n")
    w("failed=0\n")
    w("warnings=0\n")

    for i, record in enumerate(records, 1):
        action = record["action"]
        path = record["path"]
        timestamp = str(record.get("timestamp", ""))
        score = str(record.get("score", ""))
        strategy = str(record.get("strategy", ""))
        kept = str(record.get("kept") or "")
        destination = str(record.get("destination") or "")
        try:
            bytes_freed = int(record.get("bytes_freed", 0))
        except (TypeError, ValueError):
            bytes_freed = 0

        qpath = _shell_quote(path)
        qkept = _shell_quote(kept)
        qdest = _shell_quote(destination) if destination else ""

        # Sanitize values for comment lines (prevent newline injection)
        cpath = _sanitize_comment(path)
        ckept = _sanitize_comment(kept)
        caction = _sanitize_comment(action)
        ctimestamp = _sanitize_comment(timestamp)
        cstrategy = _sanitize_comment(strategy)
        cscore = _sanitize_comment(score)

        w(f"\n# --- Action {i}: {caction} ({ctimestamp}) ---\n")
        w(f"# Score: {cscore} | Strategy: {cstrategy}")
        if kept:
            w(f" | Kept: {ckept}")
        w("\n")

        if action == "moved":
            if not destination:
                w("# WARNING: No destination recorded — cannot undo this move\n")
                w(f'echo "WARNING: No destination recorded for {qpath}, skipping"\n')
                w("warnings=$((warnings + 1))\n")
                continue
            parent = str(Path(path).parent)
            qparent = _shell_quote(parent)
            w(f'if [ -e "{qdest}" ]; then\n')
            w(f'    if [ -e "{qpath}" ]; then\n')
            w(f'        echo "WARNING: {qpath} already exists, skipping"\n')
            w("        warnings=$((warnings + 1))\n")
            w("    else\n")
            w(f'        mkdir -p "{qparent}"\n')
            w(f'        mv "{qdest}" "{qpath}" && restored=$((restored + 1)) || failed=$((failed + 1))\n')
            w("    fi\n")
            w("else\n")
            w(f'    echo "WARNING: Source {qdest} not found, skipping"\n')
            w("    warnings=$((warnings + 1))\n")
            w("fi\n")

        elif action == "hardlinked":
            if not kept:
                w("# WARNING: No kept file recorded — cannot undo this hardlink\n")
                w(f'echo "WARNING: Cannot undo hardlink for {qpath} — no kept file recorded"\n')
                w("warnings=$((warnings + 1))\n")
                continue
            w(f'if [ -f "{qpath}" ] && [ -f "{qkept}" ]; then\n')
            w(f'    cp "{qkept}" "{qpath}.tmp" && mv "{qpath}.tmp" "{qpath}" \\\n')
            w("        && restored=$((restored + 1)) || failed=$((failed + 1))\n")
            w("else\n")
            w('    echo "WARNING: Cannot undo hardlink — file(s) missing"\n')
            w("    warnings=$((warnings + 1))\n")
            w("fi\n")

        elif action == "symlinked":
            if not kept:
                w("# WARNING: No kept file recorded — cannot undo this symlink\n")
                w(f'echo "WARNING: Cannot undo symlink for {qpath} — no kept file recorded"\n')
                w("warnings=$((warnings + 1))\n")
                continue
            w(f'if [ -L "{qpath}" ] && [ -f "{qkept}" ]; then\n')
            w(f'    cp "{qkept}" "{qpath}.tmp" && mv "{qpath}.tmp" "{qpath}" \\\n')
            w("        && restored=$((restored + 1)) || failed=$((failed + 1))\n")
            w("else\n")
            w('    echo "WARNING: Cannot undo symlink — file(s) missing or not a symlink"\n')
            w("    warnings=$((warnings + 1))\n")
            w("fi\n")

        elif action == "reflinked":
            if not kept:
                w("# WARNING: No kept file recorded — cannot undo this reflink\n")
                w(f'echo "WARNING: Cannot undo reflink for {qpath} — no kept file recorded"\n')
                w("warnings=$((warnings + 1))\n")
                continue
            w(f'if [ -f "{qpath}" ] && [ -f "{qkept}" ]; then\n')
            w(f'    cp "{qkept}" "{qpath}.tmp" && mv "{qpath}.tmp" "{qpath}" \\\n')
            w("        && restored=$((restored + 1)) || failed=$((failed + 1))\n")
            w("else\n")
            w('    echo "WARNING: Cannot undo reflink — file(s) missing"\n')
            w("    warnings=$((warnings + 1))\n")
            w("fi\n")

        elif action == "trashed":
            size_str = format_size(bytes_freed) if bytes_freed else "unknown size"
            w("# WARNING: Cannot auto-restore trashed file.\n")
            w(f"# Original path: {cpath}\n")
            w("# Check OS trash: ~/.Trash/ (macOS) or $XDG_DATA_HOME/Trash/ (Linux)\n")
            w(f'echo "MANUAL: Restore {qpath} from OS trash ({size_str})"\n')
            w("warnings=$((warnings + 1))\n")

        elif action == "deleted":
            size_str = format_size(bytes_freed) if bytes_freed else "unknown size"
            w("# WARNING: Permanently deleted — cannot restore.\n")
            w(f"# Original path: {cpath}\n")
            w(f"# Bytes: {bytes_freed}\n")
            w(f'echo "IRRECOVERABLE: {qpath} was permanently deleted ({size_str})"\n')
            w("warnings=$((warnings + 1))\n")

        elif action == "photos_trash":
            asset_id = _sanitize_comment(str(record.get("asset_id", "unknown")))
            filename = _sanitize_comment(str(record.get("filename", "")))
            w("# WARNING: Photos Library item moved to Recently Deleted.\n")
            w(f"# Asset ID: {asset_id}\n")
            if filename:
                w(f"# Filename: {filename}\n")
            w("# Restore from Photos app → Recently Deleted album (within 30 days)\n")
            display = _shell_quote(str(record.get("filename", path)))
            w(f'echo "MANUAL: Restore {display} from Photos Recently Deleted"\n')
            w("warnings=$((warnings + 1))\n")

        else:
            w(f"# WARNING: Unknown action type '{caction}' — skipping\n")
            w(f'echo "WARNING: Unknown action type {_shell_quote(action)} for {qpath}, skipping"\n')
            w("warnings=$((warnings + 1))\n")

    # Summary
    w("\n")
    w('echo ""\n')
    w('echo "Undo complete: $restored restored, $failed failed, $warnings warnings"\n')


def run_generate_undo(
    log_file: str,
    *,
    output_file: str | None = None,
    quiet: bool = False,
) -> None:
    """Top-level entry point called from cli.py main()."""
    console = Console(stderr=True)
    log_path = Path(log_file)

    if not log_path.exists():
        console.print(f"[red]Error: Log file not found: {log_file}[/red]")
        raise SystemExit(1)

    if output_file:
        output_path = Path(output_file)
        if output_path.exists() and log_path.samefile(output_path):
            console.print("[red]Error: --output must not be the same file as the source log[/red]")
            raise SystemExit(1)

    records, total, skipped_dry_run, skipped_malformed = parse_action_log(log_path, console=console)

    if not records:
        if not quiet:
            if total == 0:
                console.print("No action records found in log file.")
            else:
                console.print(
                    f"No actionable records in log file ({skipped_dry_run} dry-run, {skipped_malformed} malformed)."
                )
        return

    out: TextIO | None = None
    try:
        if output_file:
            try:
                out = open(output_file, "w")  # noqa: SIM115
            except OSError as exc:
                console.print(f"[red]Error writing output file: {exc}[/red]")
                raise SystemExit(1) from None

        generate_undo_script(
            records,
            log_path=log_path,
            total_records=total,
            skipped_dry_run=skipped_dry_run,
            skipped_malformed=skipped_malformed,
            output=out if out is not None else sys.stdout,
        )
    finally:
        if out is not None:
            out.close()

    if output_file and not quiet:
        console.print(f"Wrote undo script to {output_file}")
